### ISSUE TITLE
Make the charts persistent through location hash or history API

### ISSUE THREAD

**Issue by fflorent** [sverweij/mscgen_js#142] opened 2015-05-13 08:52 UTC
When entering some texts, you could make the changes persistent, using the location hash or the history API (history.push, ...).

For example, here is how the sweetjs editor stores the text in the URL: [click here](http://sweetjs.org/browser/editor.html#/*%0AWelcome to sweet.js!%0A%0AYou can play around with macro writing here on the left side and%0Ayour code will automatically be compiled on the right. This page%0Awill also save your code to localStorage on every successful%0Acompile so feel free to close the page and come back later!%0A*/%0A%0A// Here is a really simple identity macro to get started.%0A%0A// The `macro` keyword is used to create and name new macros.%0Amacro id {%0A    rule {%0A        // after the macro name, match:%0A        // %281%29 a open paren%0A        // %282%29 a single token and bind it to `$x`%0A        // %283%29 a close paren%0A        %28$x%29%0A    } => {%0A        // just return the token we bound to `$x`%0A        $x%0A    }%0A}%0Aid %28 42 %29;%0A%0A// Note that a single token to sweet.js includes matched%0A// delimiters not just numbers and identifiers. For example,%0A// an array with all of its elements counts as one token:%0Aid %28[1,2,3]%29%0A%0A// One of the really important things sweet.js does is protect%0A// macros from unintentionally binding or capturing variables they%0A// weren't supposed to. This is called hygiene and to enforce hygiene%0A// sweet.js must carefully rename all variable names.%0A%0Avar x; // note the different name on the right --->%0A%0A// For example, let's look at the swap macro that uses a temporary%0A// variable to swap the contents of two other vars:%0Amacro swap {%0A    rule {%0A        %28$x, $y%29%0A    } => {%0A        var tmp = $y;%0A        $y = $x;%0A        $x = tmp;%0A    }%0A}%0A%0Avar foo = 100;%0Avar bar = 200;%0Avar tmp = 'my other temporary variable';%0A%0Aswap %28foo, bar%29%0A%0A// Notice that even though the `tmp` variable we made outside of%0A// the macro had the same name as the `tmp` variable inside the%0A// macro, sweet.js kept them distinct.%0A)

Florent

**Comment by sverweij** [comment] 2015-05-13 10:38
Thanks for this suggestion ..

I've actually been been toying with persistency:
- In 'debug' mode it is already possible to create a location hash ([check out this example](http://sverweij.github.io/mscgen_js/?debug=true&lang=mscgen&msc=msc%20%7B%0A%20%20Alice%2C%0A%20%20Bob%2C%0A%20%20pocket%3B%0A%0A%20%20Alice%20%3D%3E%20Bob%20%5Blabel%3D%22do%20something%20funny%22%5D%3B%0A%20%20Bob%20%3D%3E%20pocket%20%5Blabel%3D%22fetch%20%28nose%20flute%29%22%5D%3B%0A%20%20Bob%20%3E%3E%20Alice%20%5Blabel%3D%22PHEEE%21%22%5D%3B%0A%20%20Alice%20%3D%3E%20Alice%20%5Blabel%3D%22hihihi%22%5D%3B%0A%7D) see below for the HOWTO). This works in most situations - I actively use this in fix-test-debug-fix cycles. It has some drawbacks:
  - The maximum length of a url is limited. It seems this differs from server to server what this maximum length is. Most sane (mscgen) sequence charts work (on github.io the url for _test: all arcs_ you'll get a _Error 756 Too long request string_).
  - With some (smaller, mainly msgenny) charts it was possible to trip up the program - it's been a while since I was able to reproduce that, though.
- I've kept it in the 'debug' (or 'beta') mode because of these drawbacks.
- I also have been toying with the idea of using *local storage* - I've run some successful tests with that (which spawned [wordywordy](https://github.com/sverweij/wordywordy) b.t.w.)

### HOWTO
- Go into 'debug mode' by passing the 'debug' parameter to mscgen_js, e.g.
http://sverweij.github.io/mscgen_js/?debug=true
- For your current chart click the button on the top right:
![image](https://cloud.githubusercontent.com/assets/4822597/7608365/134edbb0-f969-11e4-9e1e-cc97922d9509.png)
- This opens a new window that contains the URL - it seems that your suggestion to use 'history.push' would deliver a better user experience. I will look into that!

**Comment by fflorent** [comment] 2015-05-15 11:57
Looks nice. And yeah, if you could update the current URL as we type text, that would be neater :).

Florent

**Comment by sverweij** [comment] 2015-05-21 20:09
Implemented, tested (as you can see in #145) & deployed. 
- In debug mode, when auto-render is _on_ the url gets updated while you type, up to the maximum possible url length.
- github.io limits urls to 4100 characters. This can hold (uri encoded) scripts of about 2k.

Try it e.g. with [this url](https://sverweij.github.io/mscgen_js/index.html?lang=xu&debug=true&msc=msc%20%7B%0A%20%20hscale%3D%221.4%22%2C%0A%20%20wordwraparcs%3D%22true%22%3B%0A%0A%20%20sverweij%2C%0A%20%20gt%20%5Blabel%3D%22google%20translate%22%5D%2C%0A%20%20fflorent%3B%0A%0A%20%20sverweij%20%3D%3E%3E%20gt%20%5Blabel%3D%22like%20this%3F%22%5D%3B%0A%20%20gt%20%3D%3E%3E%20fflorent%20%5Blabel%3D%22Comme%20ça%2C%20monsieur%20Florent%3F%22%5D%3B%0A%20%20sverweij%20alt%20fflorent%20%5Blabel%3D%22ok%22%5D%20%7B%0A%20%20%20%20fflorent%20%3E%3E%20gt%20%5Blabel%3D%22Mais%20oui%2C%20c'est%20vraiment%20superbe!!%22%5D%3B%0A%20%20%20%20gt%20%3E%3E%20sverweij%20%5Blabel%3D%22Your%20hovercraft%20is%20full%20of%20eel.%22%5D%3B%0A%20%20%20%20sverweij%20%3D%3E%3E%20gt%20%5Blabel%3D%22I'll%20close%20the%20issue%20then%22%5D%3B%0A%20%20%20%20gt%20%3D%3E%3E%20fflorent%20%5Blabel%3D%22Tres%20bien!%20Je%20terminerai%20le%20défaut%20alors.%22%5D%3B%0A%20%20%20%20---%20%5Blabel%3D%22nok%22%5D%3B%0A%20%20%20%20fflorent%20%3E%3E%20gt%20%5Blabel%3D%22Je%20dois%20une%20suggestion%20pour%20cette%20mise%20en%20œuvre%2F%20Mais%20non%2C%20c'est%20horible!%2F%20...%22%5D%3B%0A%20%20%20%20gt%20%3E%3E%20sverweij%20%5Blabel%3D%22I%20will%20not%20buy%20this%20record.%20It%20is%20scratched.%22%5D%3B%0A%20%20%20%20sverweij%20rbox%20sverweij%20%5Blabel%3D%22back%20to%20the%20drawing%20board%22%5D%3B%0A%20%20%7D%3B%0A%7D) :-)

**Comment by fflorent** [comment] 2015-05-23 10:10
Ahah, mais oui, c'est vraiment superbe ! :)

Florent

**Comment by sverweij** [comment] 2015-05-24 15:54
I'll close the issue then. Thanks for your suggestion!

**Comment by fflorent** [comment] 2015-05-24 15:54
My pleasure, thank you for having implemented it :).

Florent

**Closed by sverweij** 2015-05-24 15:54 UTC
